name: Test
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: generate
        run: ./gradlew generateOpenApiDocs
      - name: ls
        run: ls -la ./build/docs/